### PR TITLE
changed js to es6 and changed second name to last name in read me file

### PR DESCRIPTION
**Pull request by echilaka1**

### CODE REVIEW

**Review by THEozmic — CHANGES_REQUESTED** [review]
No need to comment why you used let instead of var

**Review by THEozmic — COMMENTED** [review]
So I can already see what changes you made, no need to write a comment detailing the changes made

**Comment by echilaka1** [comment]
alright, that was just for the records from my side... noted

**Comment by THEozmic** [comment]
Okay. Update the PR and fix merge conflicts

**Review by codehakase — APPROVED** [review]

**Pull request merged**
