### PR TITLE
update to README regarding POSTMAN usage

### PR DESCRIPTION
**Pull request by voidnerd**
A lot of PH_DEVS havs been having using with using POSTMAN recently so I thought this could help out

### CODE REVIEW

**Comment by codehakase** [comment]
Thanks Boss!!

I'd like you to add extra text on this. Possible explain how to communicate with the API via postman (use of images would be nice too), I thought of doing that, but you came to the rescue.

**Comment by codehakase** [comment]
So the changes you'd make to your PR is:

- Create a sub heading specific to using POSTMAN for communicating with the API
- Steps to setting the Content-Type header
- Data type; Json or urlform-encoded

**Comment by THEozmic** [comment]
Add images?

**Comment by voidnerd** [comment]
Yeah! Imagine my surprise when I heard add images

**Comment by voidnerd** [comment]
contenttype

**Comment by THEozmic** [comment]
Hey why did you remove the image? I was simply adding that to the list of things to be changed.

**Comment by voidnerd** [comment]
@codehakase thought It would be better if he got an image with no *error 500*, you know, like a success message

**Comment by THEozmic** [comment]
Oh yes. I was about to even mention that. Wanted to check first if it was an issue with the API

**Comment by voidnerd** [comment]
So I just cleaned up the text A lil bit, he will upload a better image later.....I think

**Comment by voidnerd** [comment]
Please do check, it's weird, especially for those new to POSTMAN

**Comment by codehakase** [comment]
@NddyAndy @THEozmic I'm closing this PR, I'm creating a new issue to assign to @NddyAndy that'll be a better approach to document this

**Pull request closed without merging**
